# Generated by Django 4.1.7 on 2023-03-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.CharField(blank=True, default='default.png', max_length=50),
        ),
    ]
