# Generated by Django 4.1.7 on 2023-03-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.CharField(blank=True, default='/media/thumbnails/default.png', max_length=100),
        ),
    ]
